### ISSUE TITLE
bower 好像不能用的樣子...

### ISSUE THREAD

**Issue by ausir0726** [yyc1217/twzipcode-data#1]
看到有更改紀錄 bower 從 src/index.js 改到 dist/index.js
但是 .gitignore 把 dist 排掉了
使用 bower i 裝過，也沒看到有 dist 資料夾拉回來
這樣 bower 可以用嗎 ?

thanks.

**Comment by yyc1217** [comment]
@ausir0726 
謝謝提醒，已處理 38716a801b20f2fca96d1b32422f807a681537ec
