### ISSUE TITLE
PR 前有事情想要請教

### ISSUE THREAD

**Issue by ausir0726** [yyc1217/twzipcode-data#3]
HI 

想說再次提交 PR 前先詢問
請問有接受 PR 嗎?

修復轉檔資料後有發現兩個問題，想先討論看看在提交 PR

1.  關於新竹市與嘉義市
目前這兩個市有內建區，但是同樣都是同一組郵遞區號
300 與 600
但目前您的資料 兩個市的內區都拿掉了
雖然從 ZIPCODE 的角度來看，兩個都是同樣 ZIP CODE
但是如果你把它做成應用例如 twzipcode-vue 就會造成有時候我們想要收集到真實的地址
而並非只是確認 ZIP CODE 對於新竹市與嘉義市就無法收集到區的資料
目前這兩個區我是手動改成真實的區 
* 但在我提交的 3+2 parser 會直接把這兩個市的內區顯示出來 ( 同樣是 300 與 600 )
想討論看看 實際呈現 內區的合理性

2. 關於排序的問題
目前您的資料排序似乎是使用 ZIPCODE 的順序來做排序
但有趣的是連江縣是 209 - 212 卻被手動移到最後方
![image](https://cloud.githubusercontent.com/assets/7247064/24870297/6f4a984a-1e48-11e7-8cbd-4fbd5e98c8f6.png)
但是似乎這個選單在使用上來說，依照中華郵政使用上是會依照台灣從北到南的行政區來選
![image](https://cloud.githubusercontent.com/assets/7247064/24870348/97e2e762-1e48-11e7-9133-037a330284bd.png)
這是 yahoo購物中心的排序
![image](https://cloud.githubusercontent.com/assets/7247064/24870476/fe1a23b0-1e48-11e7-8508-512cfcc98bef.png)

所以我個人是考慮是否在 parser 的時候到中華郵政看他的 list 的順序在排序過...

以上兩點，謝謝。

如果有專案上衝突考量不方便 PR 的話，沒關係我就再建新的專案即可，謝謝。

**Comment by yyc1217** [comment]
HI @ausir0726 
1. 可以提供建議修改後的範例嗎？
```javascript
// before
    { 'id': 300, 'county': '新竹市', 'city': '新竹市' },
// after
    ?
```
2. 順序的部份我是按照**臺灣地區郵遞區號前3碼一覽表 103/12(Excel版)**的順序輸入的，的確是沒有考慮到地理位置的關係，因為也沒有明定的順序或習慣，所以若你想調整順序的話OK，但請一併調整中、英文縣市的順序保持一致性，以及放在同一個commit內，方便後續查詢。

謝謝~

**Comment by ausir0726** [comment]
hi,

1. 修改後應該是
```js
// 新竹市 before
   { 'id': 300, 'county': '新竹市', 'city': '新竹市' },
// 新竹市 after
  { id: 300, county: '新竹市', city: '東區' },
  { id: 300, county: '新竹市', city: '北區' },
  { id: 300, county: '新竹市', city: '香山區' },
// 嘉義市 before
  { id: 600, county: '嘉義市', city: '嘉義市' },
// 嘉義市 after
  { id: 600, county: '嘉義市', city: '西區' },
  { id: 600, county: '嘉義市', city: '東區' },
```
主要是有時候你在選擇鄉鎮市區，是需要那個鄉鎮市區的資料，而不是單純拿到ZIPCODE
你可能會把整包 `{ id: 300, county: '新竹市', city: '香山區' }` 存到 DB 因為那才是他完整地址
我有考慮過依照你的架構額外新增一個 unfold() 的方法 新竹市跟嘉義市展開，有需要的人再展開
因為有考慮到是否會有人已經存過 `{ 'id': 300, 'county': '新竹市', 'city': '新竹市' }` 這種資料
是不是會造成反查錯誤？ 不過這種資料本來就會變動，如果真的存到舊的好像本來就會有這問題在
不知道是不是我多慮了～

2. 謝謝，我瞭解這沒有一定的順序，只是覺得依照郵遞區號，但是連江又搬到最底好像怪怪的
如果我們可以依照中華郵政來明確定義順序，好像會更好 :D 
我修改會一併整理好再 PR

**Comment by yyc1217** [comment]
@ausir0726 這樣看來郵遞區號不是唯一的，在開發上似乎不能僅儲存郵遞區號+後續地址，例如

 郵遞區號 | 地址 
----------|--------------
 300      | XX路XX巷XX號
 300      | XX路XX巷XX號

這樣可以代表東區、北區、香山區，嘉義市也一樣；所以可以假設開發者一定會儲存

 郵遞區號 | 地址
----------|--------------
 300新竹市東區      | XX路XX巷XX號
 300新竹市香山區      | XX路XX巷XX號

所以我想就直接改成你建議的格式吧，反正應該也只有我在用這個資料XD

順序部份也按照中華郵政的順序沒有問題

**Comment by ausir0726** [comment]
郵遞區號是個神奇的東西...

Fantastic Zipcode and Where to Find Them ....

**Comment by yyc1217** [comment]
臺中市可以理解，因為302以後都被佔走了，但嘉義市明明還有601可以用

**Comment by CoffieLeo** [comment]
想請問目前新竹市跟嘉義市在顯示上的 bug 有解嗎？看起來是同個區碼造成顯示上的問題！

**Comment by ausir0726** [comment]
@CoffieLeo  這個問題後來 4/30 作者已經調整  
https://github.com/yyc1217/twzipcode-data/commit/4a0c73bf5edfc1f846bc97b678f6297c76c2a948#diff-9542886b56d37193876e8d6d9773ff6affefac9254fc9040a8375d3beef8203e
id 在分區會重複，所以儲存資料的時候不可以單存郵遞區號
'county'', 'city' 這兩個欄位也要一併存起來
在應用回 select 的時候也不能單純只用 郵遞區號做 value

**Comment by CoffieLeo** [comment]
不好意思，我可能沒表達清楚
目前除了在儲存資料會有問題外，連前端的顯示也都一樣
新竹市會顯示三個香山區，嘉義市則會顯示兩個西區！

**Comment by ausir0726** [comment]
@CoffieLeo  你說的那個應該是 twzipcode-vue 的問題
data 這邊應該是沒錯的，而且 香山 東區 西區 的郵遞區號確實也是 300
跟這邊就無關了~ 應該是去那邊討論

https://github.com/yyc1217/twzipcode-vue/issues/113

**Comment by CoffieLeo** [comment]
> @CoffieLeo 你說的那個應該是 twzipcode-vue 的問題
> data 這邊應該是沒錯的，而且 香山 東區 西區 的郵遞區號確實也是 300
> 跟這邊就無關了~ 應該是去那邊討論
> 
> [yyc1217/twzipcode-vue#113](https://github.com/yyc1217/twzipcode-vue/issues/113)

OK，感謝！

**Comment by yyc1217** [comment]
See #58
