### ISSUE TITLE
資料裡有空白

### ISSUE THREAD

**Issue by neko2891** [yyc1217/twzipcode-data#4]
https://github.com/yyc1217/twzipcode-data/blob/master/src/zh-tw/zipcodes.js

`    { 'id': 400, 'county': '臺中市', 'city': '中　區' },
    { 'id': 401, 'county': '臺中市', 'city': '東　區' },
    { 'id': 402, 'county': '臺中市', 'city': '南　區' },
    { 'id': 403, 'county': '臺中市', 'city': '西　區' },
    { 'id': 404, 'county': '臺中市', 'city': '北　區' },
`
`    { 'id': 701, 'county': '臺南市', 'city': '東　區' },
    { 'id': 702, 'county': '臺南市', 'city': '南　區' },
    { 'id': 704, 'county': '臺南市', 'city': '北　區' },
`
請問能否將空白去除？

**Comment by yyc1217** [comment]
@neko2891 可以送一個PR，或是我再找時間處理，謝謝

**Comment by yyc1217** [comment]
Done by #5
